// AUTO-GENERATED by build_status.py — do not hand-edit.
window.CC_DATA = {
  "generated": "2026-07-05",
  "agents": [
    {
      "id": "sage",
      "name": "Sage",
      "role": "SEO & Analytics Watch",
      "tagline": "She watches your search. Rankings, traffic, and what it all actually means, for every client.",
      "avatar": "assets/sage.png",
      "voice": "assets/sage-voice.m4a",
      "status": "5/6 on GA4 - reports current",
      "subjectsLabel": "Clients",
      "clients": [
        {
          "name": "Leslie M Lyon",
          "status": "GA4 live",
          "ok": true,
          "summary": "SEO + analytics monitoring, last 30 days.",
          "details": [
            "GSC: 566 clicks, 93,579 impressions (30d)",
            "GA4: 1,363 sessions (30d)",
            "Conversions: 0 (set up key events)"
          ]
        },
        {
          "name": "Elite Concrete Coatings",
          "status": "GA4 live",
          "ok": true,
          "summary": "SEO + analytics monitoring, last 30 days.",
          "details": [
            "GSC: 6 clicks, 939 impressions (30d)",
            "GA4: 2 sessions (30d)",
            "Conversions: 0 (set up key events)"
          ]
        },
        {
          "name": "Hearthstone Restoration",
          "status": "GSC only",
          "ok": true,
          "summary": "SEO monitoring, last 30 days.",
          "details": [
            "GSC: 8 clicks, 424 impressions (30d)",
            "GA4: not connected"
          ]
        },
        {
          "name": "Roatan.net \u2014 Steve Hasz",
          "status": "GA4 live",
          "ok": true,
          "summary": "SEO + analytics monitoring, last 30 days.",
          "details": [
            "GSC: 191 clicks, 29,325 impressions (30d)",
            "GA4: 1,703 sessions (30d)",
            "Conversions: 0 (set up key events)"
          ]
        },
        {
          "name": "Roatan Life Real Estate",
          "status": "GA4 live",
          "ok": true,
          "summary": "SEO + analytics monitoring, last 30 days.",
          "details": [
            "GSC: 2,737 clicks, 113,922 impressions (30d)",
            "GA4: 9,750 sessions (30d)",
            "Conversions: 0 (set up key events)"
          ]
        },
        {
          "name": "Push The Goal \u2014 Soccer Training",
          "status": "GA4 live",
          "ok": true,
          "summary": "SEO + analytics monitoring, last 30 days.",
          "details": [
            "GSC: 55 clicks, 1,099 impressions (30d)",
            "GA4: 206 sessions (30d)",
            "Conversions: 0 (set up key events)"
          ]
        }
      ]
    },
    {
      "id": "muse",
      "name": "Muse",
      "role": "Content Engine",
      "tagline": "She writes in your voice. Blogs, captions, hooks, and subhooks, on brand every time.",
      "avatar": "assets/muse.png",
      "voice": "assets/muse-voice.m4a",
      "status": "voice loaded - 5 clients, 22 scheduled",
      "subjectsLabel": "Clients",
      "clients": [
        {
          "name": "Leslie M Lyon",
          "status": "Active",
          "ok": true,
          "summary": "Blog + short-form. Voice library fully loaded.",
          "details": [
            "Scheduled WP posts: 22",
            "Drafts: 4",
            "Captions/hooks/subhooks: voice + examples captured"
          ]
        },
        {
          "name": "Hearthstone Restoration",
          "status": "Planned",
          "ok": false,
          "summary": "Captions engine planned; blog once their site is live.",
          "details": [
            "Captions from their intake forms",
            "Blog once WP + service pages finish"
          ]
        },
        {
          "name": "Jack Chinchay Real Estate",
          "status": "Onboarded",
          "ok": true,
          "summary": "Captions-only IG funnel. Veteran RE: Raider to Realtor, VA Transition Specialist.",
          "details": [
            "Brand kit: logo, colors, fonts + Facebook cover built",
            "Voice + profile captured; captions, hooks, subhooks live",
            "Lead magnet: Unlock Your VA Benefits (guide + branded PDF)",
            "Signature, bios + lender-routing rule locked in"
          ]
        },
        {
          "name": "IC Solutions (ICS)",
          "status": "Onboarded",
          "ok": true,
          "summary": "Roatán design-build firm: homes, remodels, commercial, boutique hotels, pools. Premium, trust-first voice.",
          "details": [
            "Profile + raw intake captured from onboarding call",
            "ICP: 45-65 US/Canada couples building in Roatán; trust is the story",
            "Voice: calm, premium, transparent (master-builder guide)",
            "Next: video footage, brand kit, confirm offer + DM keywords"
          ]
        },
        {
          "name": "The Real State of Roatan",
          "status": "Onboarded",
          "ok": true,
          "summary": "Cristian Lopez's Roatán real estate arm (sister to ICS). Educational, data-driven “real state of the island” voice.",
          "details": [
            "Profile + raw intake captured (two intake forms)",
            "ICP: 30-65 investors + visionaries, not retirees; Roatán vs Costa Rica",
            "Name is wordplay: the real STATE of the island (facts, data)",
            "Next: IG handle, brand kit, real data sources, CTA route"
          ]
        }
      ]
    },
    {
      "id": "vesta",
      "name": "Vesta",
      "role": "The Watchdog",
      "tagline": "She watches the watchers. Drift, rule-breaks, and anything off, she catches it and tells you.",
      "avatar": "assets/vesta.png",
      "voice": "assets/vesta-voice.m4a",
      "status": "33 files watched - all steady",
      "subjectsLabel": "Watching",
      "clients": [
        {
          "name": "Sage",
          "status": "Steady",
          "ok": true,
          "summary": "Monitoring Sage's code + workflows for drift.",
          "details": [
            "Baselined + checked weekly (Mondays 8am)",
            "Last check 2026-07-05: No drift over 1%, no rule breaks."
          ]
        },
        {
          "name": "Muse",
          "status": "Steady",
          "ok": true,
          "summary": "Monitoring Muse's voice, frameworks + rules.",
          "details": [
            "Baselined; also scans recent posts for rule breaks",
            "Last check 2026-07-05: No drift over 1%, no rule breaks."
          ]
        },
        {
          "name": "Command Central + Vesta",
          "status": "Steady",
          "ok": true,
          "summary": "Now self-watching: the dashboard, the schedulers, and Vesta herself.",
          "details": [
            "Added to her watch list this week",
            "Last check 2026-07-05: No drift over 1%, no rule breaks."
          ]
        }
      ]
    }
  ]
};
